---
- name: IOS Show commands
  hosts: "core"
  gather_facts: false
  connection: local

  vars:
      cli:
          host: "{{ ansible_host }}"
          username: "{{ username }}"
          password: "{{ password }}"

  tasks:
      - name: ios show hostnames
        iosxr_command:
            commands:
                - show run | i hostname
            provider: "{{ cli }}"
        register: output

      - name: Show Output
        debug:
            var: output.stdout_lines
