---
- name: IOS Show commands
  hosts: "all"
  gather_facts: false
  connection: local

  vars:
      cli:
          host: "{{ ansible_host }}"
          username: "{{ username }}"
          password: "{{ password }}"

  tasks:
      - name: ios show commands - Checking for iosxr routers
        ios_command:
            commands:
                - show version
            wait_for: result[0] contains iosxr
            provider: "{{ cli }}"

      - name: If iosxr - check if XRV4
        iosxr_facts:
            gather_subset: all
            provider: "{{ cli }}"
        register: output

      - name: show output of show run
        debug:
            var: output

      - name: Adding few lines to XRV4
        when: '"XRV4" in "{{ output }}"'
        iosxr_config:
            lines:
                - logging buffered 5097152
                - commit
            provider: "{{ cli }}"
        register: output

      - name: Show Output
        debug:
            var: output
